In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3, 4])
print(x)

[1 2 3 4]


In [4]:
A = np.array([[1,2],[3,4],[5,6]]) 
print(A) 

[[1 2]
 [3 4]
 [5 6]]


In [5]:
type(A)

numpy.ndarray

In [6]:
A.shape

(3, 2)

In [7]:
x.shape

(4,)

In [8]:
len(x)

4

In [9]:
A_T = A.T

In [12]:
A_T = A.transpose()

In [13]:
A_T.shape

(2, 3)

In [14]:
B = np.array([[2, 5], [7, 4], [4, 3]])
print(B)

[[2 5]
 [7 4]
 [4 3]]


In [15]:
C = A + B
print(C)

[[ 3  7]
 [10  8]
 [ 9  9]]


In [16]:
D = A + 1 
print(D)

[[2 3]
 [4 5]
 [6 7]]


In [17]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
B = np.array([[2], [4]])
print(B)

[[2]
 [4]]


In [19]:
C = np.dot(A, B)
print(C)

[[10]
 [22]
 [34]]


In [20]:
C.shape

(3, 1)

In [23]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
IA = I.dot(A)
print(IA)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [25]:
M = np.array([[1,2],[3,4]])
print(M)

[[1 2]
 [3 4]]


In [27]:
det_M = np.linalg.det(M)
print(det_M)

-2.0000000000000004


In [ ]:
M = np.array([[1,2],[3,4],[5,6]])
det_M = np.linalg.det(M)

In [32]:
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
print(A)

[[ 3  0  2]
 [ 2  0 -2]
 [ 0  1  1]]


In [33]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]


In [34]:
I = A_inv.dot(A)
print(I)

[[ 1.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
