# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [2]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
print('Update fifth value to 1')
x[4] = 1
print(x)

Update fifth value to 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
x = np.array(range(10,50))
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [10]:
x = x[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [17]:
x = np.array([1,2,0,0,4,0])
print(x)
x[np.nonzero(x)]

[1 2 0 0 4 0]


array([1, 2, 4])

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [18]:
x = np.random.rand(3,3,3)
print(x)

[[[0.25631202 0.84283054 0.75284127]
  [0.06465594 0.82590783 0.44435302]
  [0.52985021 0.38951956 0.16007059]]

 [[0.4642732  0.15114674 0.41194765]
  [0.72052104 0.06602247 0.7944075 ]
  [0.48872538 0.34507136 0.32990872]]

 [[0.6078419  0.60963077 0.79126042]
  [0.18462395 0.851549   0.11282197]
  [0.75079655 0.67359594 0.69621693]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [23]:
x = np.random.rand(10,10)
print(x)
print('='*15)
print(np.min(x))
print('='*15)
print(np.max(x))

[[0.07066597 0.7462154  0.79677361 0.91252148 0.21818184 0.7074854
  0.94384732 0.48511717 0.7056772  0.60829874]
 [0.05879537 0.00638712 0.34669391 0.93536842 0.58933491 0.99603596
  0.50154542 0.62437282 0.30471987 0.723637  ]
 [0.91588061 0.35839557 0.51521057 0.35932114 0.48215468 0.80610704
  0.78112811 0.50150417 0.24592949 0.56249165]
 [0.21348401 0.2104366  0.77175522 0.91421184 0.63818137 0.08370349
  0.25722224 0.59192672 0.5125099  0.95793527]
 [0.44943873 0.64272792 0.60376217 0.96521142 0.11598238 0.19549148
  0.62085722 0.32378168 0.75393847 0.54025169]
 [0.95487241 0.37285609 0.23999026 0.3400385  0.89126494 0.34110258
  0.33753129 0.04729584 0.99368575 0.58217248]
 [0.81047908 0.82495389 0.08631367 0.09778432 0.30316749 0.0726148
  0.73116693 0.2039561  0.91432625 0.52382289]
 [0.26171568 0.44486926 0.94638891 0.69522602 0.22466382 0.22968527
  0.68466532 0.6442423  0.19549814 0.05625932]
 [0.77380714 0.88757125 0.96634572 0.07345773 0.79041679 0.69225972
  0.49990295 0

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [25]:
x = np.random.rand(30)
print(x)
print(np.mean(x))

[0.48276355 0.34081223 0.50226535 0.8411355  0.94377347 0.30616918
 0.94759316 0.47988846 0.08901314 0.06360046 0.85933103 0.71034484
 0.1137598  0.20765132 0.40194477 0.98117233 0.27932679 0.18541785
 0.18552215 0.67144905 0.48203027 0.02892318 0.05475291 0.42408667
 0.34546041 0.89345364 0.72106196 0.70691689 0.08483557 0.66331449]
0.46659234808960126


#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [26]:
x = np.ones((10,10))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [40]:
x = np.ones((10,10))
print(x)
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
False

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [41]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [42]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 16. Normalize a 5x5 random matrix (★☆☆)

In [43]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.18155989 0.19449568 0.18599368 0.48525948 0.7433722 ]
 [0.94902825 1.         0.37899803 0.79860553 0.39966851]
 [0.96298705 0.18007964 0.38582125 0.58570548 0.35637744]
 [0.86116875 0.34861303 0.38108725 0.12049709 0.        ]
 [0.41443005 0.16393523 0.55500051 0.75825222 0.22643277]]


#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [44]:
Z = np.arange(11)

Z[(3 < Z) & (Z <= 8)] *= -1

print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 18. How to round away from zero a float array ? (★☆☆)

In [45]:
Z = np.random.uniform(-10,+10,10)

print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 3.  5.  9. -7. -2.  7.  2. -6.  8.  5.]


#### 19. Find common values between two arrays? (★☆☆)

In [46]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
No

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [49]:
def generate():
    for x in range(10):
        yield x

Z = np.fromiter(generate(),dtype=float,count=-1)

print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [50]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]

print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 23. Create a random vector of size 10 and sort it (★★☆)

In [51]:
x = np.random.random(10)

x.sort()

print(x)

[0.16333699 0.22292236 0.3298664  0.37883799 0.51494671 0.55436896
 0.58209253 0.61847715 0.63732148 0.81751133]


#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [52]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values

equal = np.allclose(A,B)

print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)

equal = np.array_equal(A,B)

print(equal)

False
False


#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [53]:
x = np.random.random(10)

x[x.argmax()] = 0

print(x)

[0.05850984 0.80841759 0.20765948 0.10082434 0.         0.50937658
 0.59690492 0.61735066 0.44623357 0.77275724]


#### 26. Find the closest value to random element in a vector? (★★☆)

In [ ]:
import numpy as np
def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

array = np.random.random(10)
print(array)
# [ 0.21069679  0.61290182  0.63425412  0.84635244  0.91599191  0.00213826
#   0.17104965  0.56874386  0.57319379  0.28719469]

value = 0.5

print(find_nearest(array, value))
# 0.568743859261

#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [59]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. Sort an array by the nth column? (★★☆)

In [60]:
Z = np.random.randint(0,10,(3,3))

print(Z)

print(Z[Z[:,1].argsort()])

[[2 7 1]
 [2 8 1]
 [9 7 1]]
[[2 7 1]
 [9 7 1]
 [2 8 1]]


#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

In [61]:
Z = np.random.randint(0,3,(3,10))

print((~Z.any(axis=0)).any())

True


#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [62]:
Z = np.array([1,2,3,4,5])

nz = 3

Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))

Z0[::nz+1] = Z

print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 31. Swap two rows of an array? (★★★)

In [63]:
A = np.arange(25).reshape(5,5)

A[[0,1]] = A[[1,0]]

print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 32. How to negate a boolean value inside an array? (★★★)

In [ ]:
import numpy as np
x = np.array([True, False])
x = ~ x
print(x)

#### 33. Find the most frequent value in an array?

In [67]:
x = np.random.randint(0,10,50)

print(np.bincount(x).argmax())

3


#### 34. Get the n largest values of an array (★★★)

In [69]:
x = np.arange(10000)
np.random.shuffle(x)
n = 5

# Slow
print (x[np.argsort(x)[-n:]])

# Fast
print (x[np.argpartition(-x,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9999 9998 9996 9995]


#### 35. Extract unique rows from a two dimensional array? (★★★)

In [66]:
array = np.array([[1, 2, 3, 4],
                  [3, 2, 4, 1],
                  [6, 8, 1, 2]])
  
print("Original array: \n",
      array)
uniqueRows = np.unique(array, 
                       axis = 0)
  
# print the output result
print('Unique Rows :',
      uniqueRows,
      sep = '\n')

Original array: 
 [[1 2 3 4]
 [3 2 4 1]
 [6 8 1 2]]
Unique Rows :
[[1 2 3 4]
 [3 2 4 1]
 [6 8 1 2]]
