In [6]:
def hello_func():
    print ('Hello Function.')

In [4]:
hello_func()

'Hello Function!'

In [8]:
hello_func()
hello_func()
hello_func()
hello_func()

Hello Function.
Hello Function.
Hello Function.
Hello Function.


In [9]:
def hello_func():
    return 'Hello Function.'
print(hello_func())

Hello Function.


In [10]:
print((len('Test')))

4


In [11]:
print(hello_func().upper())

HELLO FUNCTION.


In [16]:
def hello_func(greeting, name = 'You'):
    return '{}, {}.'.format(greeting, name)
print(hello_func('Hi'))

Hi, You.


In [17]:
def student_info(*args, **kwargs):
    print(args)
    print(kwargs)
student_info('Math', 'Art', name = 'John', age = 22)

('Math', 'Art')
{'name': 'John', 'age': 22}


In [20]:
courses = ['Math', 'Art']
info = {'name': 'John', 'age':22}
student_info(*courses, **info)

('Math', 'Art')
{'name': 'John', 'age': 22}


In [ ]:
# Number of days per month. First value placeholder for indexing purposes.

In [22]:
month_days = [0, 31,28, 31, 30, 31, 30, 31,31,30, 31, 30, 31]

In [23]:
def is_leap(year):
    """Return True for leap years, False for non-leap years."""
    return year % 4 == 0 and (year %  100 != 0 or year % 400 ==0)

In [25]:
def days_in_month(year, month):
    """Return number of days in that month in that year."""
    # year 2017
    # month 2
    
    if not 1 <= month <= 12:
        return 'Invalid Month'
    if month == 2 and is_leap(year):
        return 29
    return month_days[month]
print(days_in_month(2017, 2))

28


In [26]:
import numpy as np

In [38]:
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [30]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [32]:
# Get Dimension
b.ndim

2

In [34]:
# Get Shape
b.shape


(2, 3)

In [39]:
#Get Type
a.dtype

dtype('int16')

In [44]:
# Get Size
a.itemsize
b.itemsize

8

In [45]:
# Get total size
a.nbytes

6

In [50]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [51]:
# Get a specific element [r, c]
a[1, 5]

13

In [52]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [53]:
# get a specific column
a[:,2]

array([ 3, 10])

In [54]:
# Getting a little more fancy [startindex:endindex:setpsize]
a[0, 1:6:2]

array([2, 4, 6])

In [56]:
a[1,5] = 20
print(a)
a[:,2] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [ ]:
* 3-d example

In [57]:
b = np.array([[[1,2], [3,4],[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [60]:
# Get specific element (work outside in)
b[0,1,1]

4

In [61]:
# replace
b[:,1,:] = [[9,9,9], [8,8,8]]

ValueError: could not broadcast input array from shape (2,3) into shape (1,2)

In [62]:
# All 0s matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [64]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [66]:
# Any other number
np.full((2,2), 99,dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [69]:
# any other number (full_like)
np.full_like(a.shape,4)

array([4, 4])

In [70]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.66672379, 0.43827577],
       [0.32400261, 0.6397138 ],
       [0.67823342, 0.28622072],
       [0.82802669, 0.96150811]])

In [71]:
# Random Integer values
np.random.randint(7,size = (3,3))

array([[6, 6, 3],
       [4, 2, 3],
       [1, 0, 5]])

In [72]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [75]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Becareful when copying arrays!

In [78]:
a = np.array([1,2,3])
b = a.copy()
b [0] =100
print (a)

[1 2 3]


In [81]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [82]:
a+=2
a

array([3, 4, 5, 6])

In [83]:
a -2

array([1, 2, 3, 4])

In [84]:
a *2

array([ 6,  8, 10, 12])

In [85]:
a/2

array([1.5, 2. , 2.5, 3. ])

In [86]:
b = np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

In [89]:
a**2

array([ 9, 16, 25, 36], dtype=int32)

In [91]:
# Take the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [ ]:
# Linear Algebra

In [94]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [95]:
# fIND THE DETERMINANT
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
# Statistics

In [97]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
np.min(stats, axis=1)

array([1, 4])

In [100]:
np.max(stats, axis=1)

array([3, 6])

In [101]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [ ]:
# REORGIANZING ARRAYS

In [103]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [104]:
# VERTICALLY STACKING VECTORS
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [105]:
# HORIZONTAL STACK
h1 = np.ones((2,4))
h2= np.zeros((2,2))

np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [ ]:
# LOAD DATA FROM A FILE

In [ ]:
# BOOLEAN MASKING AND AVANCEED INDEXING

In [ ]:
filedata[filedata > 50]

In [ ]:
# you can index with a list in NumPy

In [ ]:
a[2:4, 0:2]
a[[0,1,2,3], [1,2,3,4]]
a[[0,4,5], 3:]

In [111]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [112]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-112-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False